GoogleCloudPlatform/service-extensions

samples/add_header/plugin.cc, samples/add_header/plugin.rs
Purpose: To add region tags comments for the purpose of embedding code in Cloud Docs.
The new region tag is `serviceextensions_add_header`. This region tag is create from a string concatenation of repo name(`serviceextensions_`) and sample's folder name(`add_header`).
New region tags are added to the following files
* samples/add_header/plugin.cc#L15
* samples/add_header/plugin.rs#L15
=> docs: add region tags for add_header example

.bazelrc, BUILD, README.md, WORKSPACE, plugins.bzl, samples/add_header/BUILD, samples/add_header/test.cc, samples/config_denylist/BUILD, samples/config_denylist/test.cc, samples/noop_logs/BUILD, samples/noop_logs/test.cc, samples/query_log/BUILD, samples/query_log/test.cc, samples/regex_rewrite/BUILD, samples/regex_rewrite/test.cc, test/BUILD, test/framework.cc, test/framework.h
- rework .bazelrc: add benchmarking/testing flags, remove cruft
- add static registration macros for unit tests and benchmarks, so we automatically run them for all engines + plugin flavors
- add proxy_wasm_test macro to support tests + benchmarks in one file
- optimize the test framework for benchmarks (no logging, no tracing)
- write sample benchmarks for add_header and regex_rewrite
- update README with benchmarking command
I included a small unrelated change to neuter BoringSSL's RNG in tests.
=> feat: Add benchmarking support to the samples repository

plugins/samples/add_header/plugin.cc, plugins/samples/add_header/plugin.rs, plugins/samples/config_denylist/plugin.cc, plugins/samples/config_denylist/plugin.rs, plugins/samples/noop_logs/plugin.cc, plugins/samples/noop_logs/plugin.rs, plugins/samples/query_log/plugin.cc, plugins/samples/query_log/plugin.rs, plugins/samples/regex_rewrite/plugin.cc, plugins/samples/regex_rewrite/plugin.rs
PR adds following docs changes & no code updates
1. Update region tags to include `plugin` key word
2. Add new region tags to code samples
Similar PR: https://github.com/GoogleCloudPlatform/python-docs-samples/pull/10916
Issue Request: https://github.com/GoogleCloudPlatform/python-docs-samples/issues/10788
This update can ensure that Callout and Plugin (add_header & other) samples are distinguishable by region tag name.
=> docs: update region tags

.gitignore, plugins/samples/regex_rewrite/plugin.rs
Some Rust cleanup. CI still broken due to https://github.com/proxy-wasm/proxy-wasm-cpp-host/issues/364 and https://github.com/envoyproxy/envoy/issues/29311.
=> fix: Improve recipe handling plugin root variables. Fix gitignore.

plugins/samples/add_header/plugin.cc, plugins/samples/add_header/plugin.rs, plugins/samples/add_header/tests.textpb, plugins/test/BUILD, plugins/test/framework.h, plugins/test/runner.proto
Also expand header mutation testing (include updates, removals).
Branched off #38. Fixes #9.
=> fix: treat header names as case insensitive

plugins/test/framework.h
Without this fix the context calls closeStream() which aborts with an "unimplemented" error.
=> fix: Better handling for VM/stream failures.

callouts/python/extproc/example/add_header/service_callout_example.py, callouts/python/extproc/example/redirect/Dockerfile, callouts/python/extproc/example/redirect/service_callout_example.py, callouts/python/extproc/service/callout_server.py, callouts/python/extproc/service/callout_tools.py, callouts/python/extproc/tests/redirect_test.py
Adding the redirect sample as a standalone example
7. Perform a HTTP redirect
UC7 - For a given URL - redirect to another URL
New PR based on the new structure from #55 and requested changes in #53 to use ImmediateResponse
- Minor fix in the add_header to use the new callout_tools instead of callout_server
=> feat: Adding new sample for the python callouts

.github/CODEOWNERS
Fix CODEOWNERS reviewers to cover plugins/ and callouts/ samples dirs.
=> fix: Update CODEOWNERS to match directory shuffle

plugins/README.md, plugins/WORKSPACE, plugins/plugins.bzl, plugins/quiche.patch, plugins/samples/testing/BUILD, plugins/samples/testing/plugin.cc, plugins/samples/testing/plugin.rs, plugins/samples/testing/request_headers.data, plugins/samples/testing/response_headers.data, plugins/samples/testing/tests.textpb, plugins/test/BUILD, plugins/test/dynamic_test.cc, plugins/test/dynamic_test.h, plugins/test/framework.cc, plugins/test/framework.h, plugins/test/package/licenses/LICENSE.googleurl, plugins/test/package/licenses/LICENSE.quiche, plugins/test/package/licenses/README.md, plugins/test/runner.proto, plugins/test/runner_main.cc
Uses the Quiche Balsa library to parse HTTP1 headers and converts 
them into HTTP2 headers like ext_proc servers would see.
Also includes a large number of minor features and fixes:
- A testing showcase sample that exercises most test runner features
- An option to set the (fixed) host timestamp + tests for static time
- Generic string matching on serialized headers (key: value)
- Improve string matcher output format for clarity
- Supporting reading test files from relative paths
- A `--nobench` flag to turn off all benchmarking (faster iteration)
- Small fix to `--loglevel` flag overrides
Checks:
=> feat: Read serialized HTTP1 headers from string or file

plugins/test/dynamic_test.cc
Various small fixes
- error when header key is omitted
- don't benchmark stream teardown
=> fix: Plugin testing sharp edges

callouts/python/extproc/example/basic_callout_server.py, callouts/python/extproc/example/normalize_header/service_callout_example.py, callouts/python/extproc/tests/basic_grpc_test.py, callouts/python/extproc/tests/ext_proc_client_test.py, callouts/python/extproc/tests/normalize_header_test.py
Envoy passes the host header with the key `authority` instead of `host`. Several of the sample Python files used the incorrect `host` key instead of `authority`.
This pull request fixes a number of these errors.
=> updating the host fields with authority

callouts/python/extproc/service/callout_server.py
A few small typos I noticed while documenting.
=> fix: update callout_server.py for grammar

plugins/README.md, plugins/samples/overwrite_errcode/BUILD, plugins/samples/overwrite_errcode/plugin.cc, plugins/samples/overwrite_errcode/tests.textpb
This plugin is a create HTTP cookie showcase.
Technically, this is performed by replacing the 5XX error code response to 4XX. 
This examples contains only a C++ version.
=> feat: create a C++ sample plugin for overwriting error codes from 5XX  to 4XX classes.

plugins/samples/block_request/BUILD, plugins/samples/block_request/plugin.cc, plugins/samples/block_request/tests.textpb, plugins/samples/set_cookie/BUILD, plugins/samples/set_cookie/plugin.cc, plugins/samples/set_cookie/tests.textpb
Given that now it's possible to use `absl::Random` in plugin examples, thanks to [chore: Update C++ dependencies, enable RE2 plugin by martijneken · Pull Request #124 · GoogleCloudPlatform/service-extensions](https://github.com/GoogleCloudPlatform/service-extensions/pull/124) .   
The `set_cookie` and the `block_request` plugins should be updated to start using it instead of timestamp.
=> chore: change set_cookie and block_request plugins to use absl::Random instead of timestamp to generate IDs

plugins/README.md, plugins/samples/check_pii/BUILD, plugins/samples/check_pii/plugin.cc, plugins/samples/check_pii/tests.textpb
This plugin is a PII on response check showcase.
Technically, this is performed by checking the response http headers, and the response body for the presence of credit card numbers. If found, the initial numbers will be masked.
This examples contains only a C++ version.
=> feat: adding new c++ sample plugin to check for PII on responses

plugins/plugins.bzl
fix: Check for incorrect return-type during plugin compilation
=> fix:Check for incorrect return-type during plugin compilation

plugins/test/package/Dockerfile
The latest Bazelisk version has extra dependencies and needs Go 1.21
=> fix: Specify a bazelisk version in Docker builds (v1.21.0)

plugins/samples/overwrite_errcode/BUILD, plugins/samples/overwrite_errcode/plugin.go
Go version for the overwriting error codes.
This is performed by replacing the 5XX error code response to 4XX.
=> feat: create a Go sample plugin for overwriting error codes from 5XX to 4XX classes.

plugins/samples/add_header/BUILD, plugins/samples/add_header/plugin.go
This plugin is an add header showcase.
Add new request headers ("Message: hello")
Replace existing request headers ("Welcome: warm")
Conditionally append to response headers (adds "bar" if Message header is "foo")
Remove response headers (removes "Welcome" header)
This example contains only a Go version.
=> feat: create a Go sample plugin for add header

plugins/samples/ab_testing/BUILD, plugins/samples/ab_testing/plugin.go
This plugin is a block request with particular URL/header showcase.
Technically, this is performed by the following hashing algorithm:
1. The user ID is hashed into an integer value between 0 and 99.
1. This integer value is compared to a predefined percentile (e.g., 50%).
1. If the hash value is less than or equal to the percentile, the request is served by v2 file. Otherwise, it is served by its original file.
This examples contains only a Go version.
=> feat: create a Go sample plugin for A/B testing

plugins/samples/docs_plugin_config/BUILD, plugins/samples/docs_plugin_config/plugin.go
This plugin is a Go version from the already implemented in C++ and Rust docs_plugin_config.
This examples contains only a Go version.
=> feat: create a Go sample for the docs plugin config

plugins/samples/add_header/tests.textpb, plugins/samples/regex_rewrite/tests.textpb
Benchmarks in tests caused ASan and TSan tests to occasionally fail due to timeouts.
=> fix: Remove benchmarks from sample tests

plugins/README.md, plugins/samples/log_calls/tests.textpb, plugins/test/dynamic_test.cc, plugins/test/dynamic_test.h, plugins/test/framework.cc, plugins/test/framework.h, plugins/test/runner_main.cc
Adds stats for memory / logging / binary size in bytes.
The memory stats could use further improvement since they
1. Don't account for stream parallelism
2. Don't give insight into wasm-side allocations
But this is a good enough starting point.
Also adds a flag to optionally disable unit tests.
=> feat: Add custom stats to benchmarking

plugins/WORKSPACE
Pick up https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/pull/174
=> chore: Update cpp-sdk to pick up C++ RAM improvement

plugins/test/framework.cc, plugins/test/framework.h
The response body callback is not supported since at that point, the body may already be streaming to the downstream client. It is fair to send an immediate response from the request body callback; however.
=> Support local response from request body callback

plugins/test/framework.cc
fix: Prevent additional callbacks after immediate response
=> fix: Prevent additional callbacks after immediate response

plugins/test/dynamic_test.cc, plugins/test/framework.cc, plugins/test/framework.h
Fixes #227. Quoting from that:
"The test runner always passes false for end_of_stream for each body chunk, for both the request body and the response body. It should actually pass true on the last body chunk...It is possible to have end_of_stream = false on the last body chunk if there are HTTP trailers, but the test runner doesn't support HTTP trailers. Therefore for the test runner, end_of_stream should be true for the last body chunk."
Changed files build: I ran `bazel build --config=clang test:all`, with clang-16.
=> fix: Pass end_of_stream bit to onResponseBody and onRequestBody calls in unit testing framework

plugins/test/BUILD, plugins/test/dynamic_test.cc, plugins/test/dynamic_test.h, plugins/test/runner.proto, plugins/test/runner_main.cc
Adds two command-line flags to the plugin tester:
--num_additional_streams
Specifies the number of additional streams to instantiate in benchmarks.
--additional_stream_advance_rate
If additional streams are configured, specifies how many background
streams to advance the state of in each benchmark cycle.
Additional streams are instantiated and advanced outside of the benchmark timer. They pass the same headers and body inputs to the plugin that are specified for the test case being benchmarked.
Example usage:
```
$ cd plugins/
$ bazelisk build ...
$ bazel-bin/test/runner \
--proto=samples/add_response_header/tests.textpb \
--plugin=bazel-bin/samples/add_response_header/plugin_cpp.wasm \
--num_additional_streams=1000 \
--additional_stream_advance_rate=5
```
The num_additional_streams and …
=> feat: add support for running background streams in plugin benchmarks

README.md
Wasm plugins have been generally available on Google Cloud application load balancers since July 1, 2025.
=> docs: Update README support statement re: Wasm plugins.
