GoogleCloudPlatform/service-extensions

samples/config_denylist/plugin.rs, samples/noop_logs/plugin.rs
Fixes #<issue_number_goes_here>
> It's a good idea to open an issue first for discussion.
=> docs: add region tag comments

README.md, plugins/Cargo.Bazel.lock, plugins/WORKSPACE
=> fix: Fix clang/CI builds with v8 patch and rules_rust workaround.

callouts/python/extproc/example/add_custom_response/Dockerfile, callouts/python/extproc/example/add_custom_response/service_callout_example.py, callouts/python/extproc/example/cloud_log/Dockerfile, callouts/python/extproc/example/cloud_log/service_callout_example.py, callouts/python/extproc/service/callout_server.py, callouts/python/extproc/tests/add_custom_response_test.py, callouts/python/extproc/tests/cloud_log_test.py, callouts/python/requirements.txt
Fixes #49
5. Generate custom HTTP responses on arbitrary field
6. Log a custom variable to cloud logging
=> feat: Adding new samples for the python callouts

callouts/python/extproc/example/set_cookie/Dockerfile, callouts/python/extproc/example/set_cookie/service_callout_example.py, callouts/python/extproc/tests/basic_grpc_test.py, callouts/python/extproc/tests/normalize_header_test.py, callouts/python/extproc/tests/set_cookie_test.py, callouts/python/extproc/tests/update_header_test.py
Fixes #67
1. Set a cookie for a given client request
=> feat: Adding use-case 12 in the callout scructure (#67)

callouts/python/extproc/example/Dockerfile, callouts/python/extproc/example/add_custom_response/Dockerfile, callouts/python/extproc/example/add_header/Dockerfile, callouts/python/extproc/example/cloud_log/Dockerfile, callouts/python/extproc/example/jwt_auth/Dockerfile, callouts/python/extproc/example/normalize_header/Dockerfile, callouts/python/extproc/example/redirect/Dockerfile, callouts/python/extproc/example/set_cookie/Dockerfile, callouts/python/extproc/example/update_header/Dockerfile
=> fix: license for Dockerfile.

README.md, callouts/python/README.md, callouts/python/extproc/example/add_body/service_callout_example.py, callouts/python/extproc/example/basic_callout_server.py, callouts/python/extproc/tests/README.md, callouts/python/extproc/tests/add_body_test.py
This doesn't change any behaviors. It clears a few obvious issues I've encountered while trying to use the repository.
1. Proper links to documents from README.md.
2. Code formatting in two README.md files.
3. Typos, e.g. "reciving".
4. Fixed the `add_body` example and added tests for it.
=> fix: Address a few obvious issues

callouts/python/buf.gen.yaml, callouts/python/buf_dev.gen.yaml
=> fix: Adding back in missing dev generate file, making python versions consistent

.github/workflows/scorecard.yml
Steps: https://github.com/ossf/scorecard-action#installation
=> feat: Add OSSF Scorecard action

callouts/python/extproc/example/ext_proc_client.py
=> fix: Renaming key to cert.

.github/workflows/plugins-publish-tester.yml
Add a public-image-${SHA} tag to each image.
=> feat: Add a public-image-${SHA} tag to each image

.github/workflows/plugins-publish-tester.yml, callouts/go/README.md, callouts/go/extproc/cmd/example/main.go, callouts/go/extproc/examples/add_body/add_body.go, callouts/go/extproc/examples/add_header/add_header.go, callouts/go/extproc/examples/basic_callout_server/basic_callout_server.go, callouts/go/extproc/examples/client/client_test.go, callouts/go/extproc/examples/jwt_auth/jwt_auth.go, callouts/go/extproc/examples/redirect/redirect.go, callouts/go/go.mod, callouts/python/README.md, docs/index.html, docs/python/conf.py, docs/python/readme/quick_start.rst, plugins/Cargo.Bazel.lock, plugins/Cargo.lock, plugins/Cargo.toml, plugins/README.md, plugins/WORKSPACE
subject: s/service-extensions-samples/service-extensions/
signed-off-by: Shriram Rajagopalan <shriramr@google.com>
=> chore: s/service-extensions-samples/service-extensions/

plugins/README.md
=> chore: Docs tweaks + clarifications

plugins/WORKSPACE
=> chore: Fix broken com_google_googleurl dependency

plugins/README.md
docs: Clarify plugin build instructions
=> docs: Clarify plugin build instructions

callouts/python/extproc/example/Dockerfile
No Doc changes.
No Functional changes.
=> fix: docker typo

plugins/README.md
=> chore: Add anchor tag at the top of the README

plugins/samples/ab_testing/BUILD, plugins/samples/add_custom_response/BUILD, plugins/samples/add_header/BUILD, plugins/samples/block_request/BUILD, plugins/samples/body_chunking/BUILD, plugins/samples/check_pii/BUILD, plugins/samples/config_denylist/BUILD, plugins/samples/jwt_auth/BUILD, plugins/samples/log_query/BUILD, plugins/samples/normalize_header/BUILD, plugins/samples/overwrite_errcode/BUILD, plugins/samples/overwrite_header/BUILD, plugins/samples/redirect/BUILD, plugins/samples/regex_rewrite/BUILD, plugins/samples/set_cookie/BUILD, plugins/samples/set_query/BUILD, plugins/samples/testing/BUILD
=> chore: Remove unnecessary ProxyWasm contrib deps

plugins/samples/redirect/BUILD, plugins/samples/redirect/plugin.go
Go version for the redirect sample.
=> feat: create a Go sample plugin to perform a HTTP response redirect

plugins/WORKSPACE, plugins/samples/jwt_auth/BUILD, plugins/samples/jwt_auth/plugin.cc, plugins/samples/jwt_auth/plugin.go, plugins/samples/jwt_auth/tests.textpb
Go version for the JWT auth.
Minor changes for the c++ code and tests so it can be used across all languagues.
=> feat: create a Go sample plugin for JWT authorization

callouts/python/extproc/example/dynamic_forwarding/service_callout_example.py, callouts/python/extproc/service/callout_server.py, callouts/python/extproc/service/callout_tools.py, callouts/python/extproc/tests/dynamic_forwarding_test.py
Changes:
Added new scenario for dynamic_forwarding.
=> feat: Dynamic forwarding python example

callouts/python/extproc/example/dynamic_forwarding/service_callout_example.py, callouts/python/extproc/service/callout_tools.py
Fixes Addresses comments from https://github.com/GoogleCloudPlatform/service-extensions/pull/198
=> fix: Update build_dynamic_forwarding_metadata to use simple proto functions

plugins/samples/local_reply/package/Dockerfile, plugins/samples/local_reply/package/licenses/LICENSE.abseil, plugins/samples/local_reply/package/licenses/LICENSE.proxywasm
chore: Add licenses for hello world plugin.
=> chore: Add licenses for hello world plugin.
